services:
  nginx:
    image: nginx:alpine
    container_name: nginx_laravel
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
      - "8084:8084"
      - "8095:8095"
      - "8086:8086"
      - "8089:8089"
      - "8099:8099"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites:/etc/nginx/conf.d:ro
      - ./letsencrypt:/etc/ca-certificates:ro
      - ./logs:/var/log/nginx
      - ./apps:/var/www/apps:ro
    depends_on:
      - php74
      - php81
      - php84
    restart: unless-stopped
    networks:
      - php-network

  php74:
    build: ./php74
    container_name: php74_fpm
    volumes:
      - ./apps:/var/www/apps
    working_dir: /var/www/apps
    restart: unless-stopped
    networks:
      - php-network
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  php81:
    build: ./php81
    container_name: php81_fpm
    volumes:
      - ./apps:/var/www/apps
    working_dir: /var/www/apps
    restart: unless-stopped
    networks:
      - php-network
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  php82:
    build: ./php82
    container_name: php82_fpm
    volumes:
      - ./apps:/var/www/apps
    working_dir: /var/www/apps
    restart: unless-stopped
    networks:
      - php-network
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  php84:
    build: ./php84
    container_name: php84_fpm
    volumes:
      - ./apps:/var/www/apps
    working_dir: /var/www/apps
    restart: unless-stopped
    networks:
      - php-network
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

networks:
  php-network:
    driver: bridge